resolver: nightly-2018-05-04

packages:
- .

extra-deps:
- multivector-0.1.0.0
- txt-0.0.2.1
- util-0.1.7.0
- git: https://github.com/strake/bytestring.hs
  commit: f0619666f189b22b15d7607ec0d5e4c305d54fcb
